Repository transloadit/uppy, pull requests merged in 2021-06, with the labels that each got.

#2913 Some polish
  website/src/_posts/2021-04-1.29.md
Labels: Website

#2918 Mention the file name in `exceedsSize` error message
  packages/@uppy/core/src/index.js
  packages/@uppy/core/src/index.test.js
  packages/@uppy/locales/src/en_US.js
  packages/@uppy/locales/src/nl_NL.js
Labels: Core

#2914 Expose drag-drop events
  packages/@uppy/drag-drop/src/index.js
  packages/@uppy/drag-drop/types/index.d.ts
  packages/@uppy/drag-drop/types/index.test-d.ts
  website/src/docs/dragdrop.md
Labels: Drag Drop, Feature

#2891 Allowed HTML Attributes to be passed via props
  packages/@uppy/react/src/Dashboard.d.ts
  packages/@uppy/react/src/Dashboard.js
  packages/@uppy/react/src/DashboardModal.d.ts
  packages/@uppy/react/src/DashboardModal.js
  packages/@uppy/react/src/DragDrop.d.ts
  packages/@uppy/react/src/DragDrop.js
  packages/@uppy/react/src/ProgressBar.d.ts
  packages/@uppy/react/src/ProgressBar.js
  packages/@uppy/react/src/StatusBar.d.ts
  packages/@uppy/react/src/StatusBar.js
  packages/@uppy/react/src/getHTMLProps.js
Labels: React

#2926 Upgrade Preact to latest
  examples/custom-provider/package-lock.json
  examples/custom-provider/package.json
  package-lock.json
  packages/@uppy/box/package.json
  packages/@uppy/core/package.json
  packages/@uppy/core/src/Plugin.js
  packages/@uppy/dashboard/package.json
  packages/@uppy/dashboard/src/components/FileCard/index.js
  packages/@uppy/dashboard/src/components/Slide.js
  packages/@uppy/dashboard/src/components/VirtualList.js
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/drag-drop/package.json
  packages/@uppy/dropbox/package.json
  packages/@uppy/facebook/package.json
  packages/@uppy/file-input/package.json
  packages/@uppy/google-drive/package.json
  packages/@uppy/image-editor/package.json
  packages/@uppy/informer/package.json
  packages/@uppy/instagram/package.json
  packages/@uppy/onedrive/package.json
  packages/@uppy/progress-bar/package.json
  packages/@uppy/provider-views/package.json
  packages/@uppy/provider-views/src/CloseWrapper.js
  packages/@uppy/screen-capture/package.json
  packages/@uppy/screen-capture/src/StopWatch.js
  packages/@uppy/status-bar/package.json
  packages/@uppy/unsplash/package.json
  packages/@uppy/url/package.json
  packages/@uppy/webcam/package.json
  packages/@uppy/zoom/package.json
  test/endtoend/create-react-app/package-lock.json
  test/endtoend/create-react-app/test.js
Labels: 2.0, dependencies

#2943 locales: remove es_GL that was kept for backwards-compat
  bin/locale-packs.js
  packages/@uppy/locales/legacy/README.md
  packages/@uppy/locales/legacy/nb_NO.js
  packages/@uppy/locales/src/es_GL.js
  website/inject.js
Labels: 2.0

#2942 dashboard: set default trigger to null instead of a specific class selector
  packages/@uppy/dashboard/src/index.js
  website/src/docs/dashboard.md
Labels: 2.0

#2932 ci: remove Node.js v10.x, add v16.x
  .github/workflows/ci.yml
Labels: 2.0

#2944 Split `Plugin` into `BasePlugin` and extended `UIPlugin`
  BACKLOG.md
  examples/custom-provider/client/MyCustomProvider.js
  packages/@uppy/aws-s3-multipart/src/index.js
  packages/@uppy/aws-s3/src/index.js
  packages/@uppy/box/src/index.js
  packages/@uppy/core/src/BasePlugin.js
  packages/@uppy/core/src/UIPlugin.js
  packages/@uppy/core/src/UIPlugin.test.js
  packages/@uppy/core/src/index.js
  packages/@uppy/core/src/index.test.js
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/drag-drop/src/index.js
  packages/@uppy/drop-target/src/index.js
  packages/@uppy/dropbox/src/index.js
  packages/@uppy/facebook/src/index.js
  packages/@uppy/file-input/src/index.js
  packages/@uppy/form/src/index.js
  packages/@uppy/golden-retriever/src/index.js
  packages/@uppy/google-drive/src/index.js
  packages/@uppy/image-editor/src/index.js
  packages/@uppy/informer/src/index.js
  packages/@uppy/instagram/src/index.js
  packages/@uppy/onedrive/src/index.js
  packages/@uppy/progress-bar/src/index.js
  packages/@uppy/provider-views/README.md
  packages/@uppy/react/src/__mocks__/DashboardPlugin.js
  packages/@uppy/react/src/__mocks__/DragDropPlugin.js
  packages/@uppy/react/src/__mocks__/FileInputPlugin.js
  packages/@uppy/react/src/__mocks__/ProgressBarPlugin.js
  packages/@uppy/react/src/__mocks__/StatusBarPlugin.js
  packages/@uppy/redux-dev-tools/src/index.js
  packages/@uppy/robodog/src/AttachFileInputs.js
  packages/@uppy/robodog/src/TransloaditFormResult.js
  packages/@uppy/robodog/src/TransloaditResultsPlugin.js
  packages/@uppy/screen-capture/src/index.js
  packages/@uppy/status-bar/src/index.js
  packages/@uppy/thumbnail-generator/src/index.js
  packages/@uppy/thumbnail-generator/src/index.test.js
  packages/@uppy/transloadit/src/index.js
  packages/@uppy/tus/src/index.js
  packages/@uppy/unsplash/src/index.js
  packages/@uppy/url/src/index.js
  packages/@uppy/webcam/src/index.js
  packages/@uppy/xhr-upload/src/index.js
  packages/@uppy/zoom/src/index.js
  test/mocks/acquirerPlugin1.js
  test/mocks/acquirerPlugin2.js
  test/mocks/invalidPluginWithoutId.js
  test/mocks/invalidPluginWithoutType.js
  website/src/_posts/2020-03-custom-providers.md
  website/src/docs/writing-plugins.md
Labels: 2.0, Core

#2948 transloadit: fix unhandled promise rejections
  packages/@uppy/core/src/index.js
  packages/@uppy/transloadit/src/index.js
Labels: 2.0

#2955 Remove `sync` option from `VirtualList` & update `UIPlugin` render
  packages/@uppy/core/src/UIPlugin.js
  packages/@uppy/dashboard/src/components/VirtualList.js
Labels: 2.0, Core

#2961 Create `getObjectOfFilesPerState` for plugins
  packages/@uppy/core/src/index.js
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/status-bar/src/index.js
Labels: 2.0, Core, Dashboard, Status Bar

#2947 Remove IE polyfills and special casing
  .browserslistrc
  .github/workflows/ci.yml
  .github/workflows/end-to-end.yml
  CHANGELOG.md
  README.md
  bin/build-bundle.js
  examples/dev/index.js
  package.json
  packages/@uppy/aws-s3/package.json
  packages/@uppy/aws-s3/src/index.js
  packages/@uppy/companion-client/package.json
  packages/@uppy/companion-client/src/Provider.js
  packages/@uppy/core/src/loggers.js
  packages/@uppy/dashboard/package.json
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/dashboard/src/index.test.js
  packages/@uppy/image-editor/src/Editor.js
  packages/@uppy/provider-views/src/ProviderView/ProviderView.js
  packages/@uppy/robodog/bundle.js
  packages/@uppy/thumbnail-generator/package.json
  packages/@uppy/thumbnail-generator/src/index.js
  packages/@uppy/transloadit/package.json
  packages/@uppy/transloadit/src/Client.js
  packages/@uppy/utils/package.json
  packages/@uppy/utils/src/AbortController.js
  packages/@uppy/utils/src/dataURItoBlob.js
  packages/@uppy/utils/src/isTouchDevice.js
  packages/@uppy/webcam/src/index.js
  packages/uppy/bundle.js
  test/endtoend/chaos-monkey/main.js
  test/endtoend/create-react-app/package-lock.json
  test/endtoend/i18n-drag-drop/main.js
  test/endtoend/providers/main.js
  test/endtoend/thumbnails/main.js
  test/endtoend/transloadit/main.js
  test/endtoend/tus-dashboard/main.js
  test/endtoend/tus-drag-drop/main.js
  test/endtoend/typescript/main.ts
  test/endtoend/url-plugin/main.js
  test/endtoend/wdio.remote.conf.js
  test/endtoend/xhr-limit/main.js
  website/src/_posts/2021-XX-XX.md
  website/src/docs/index.md
  website/src/docs/uppy.md
  website/src/examples/dashboard/app.es6
  website/src/examples/dragdrop/app.es6
  website/src/examples/statusbar/app.es6
  website/src/examples/transloadit/app.es6
  website/src/examples/xhrupload/app.es6
Labels: 2.0

#2945 expect built-in support for `MediaDevices` API
  packages/@uppy/screen-capture/src/index.js
  packages/@uppy/webcam/src/index.js
Labels: 2.0

#2967 Resolve or remove miscellaneous todos
  bin/locale-packs.js
  packages/@uppy/companion-client/src/Provider.js
  packages/@uppy/companion/src/companion.js
  packages/@uppy/companion/src/server/controllers/connect.js
  packages/@uppy/companion/src/server/controllers/send-token.js
  packages/@uppy/companion/src/server/provider/drive/index.js
  packages/@uppy/companion/src/server/provider/index.js
  packages/@uppy/companion/src/standalone/helper.js
  packages/@uppy/companion/test/__tests__/callback.js
  packages/@uppy/core/src/index.js
  packages/@uppy/dashboard/src/components/Slide.js
  packages/@uppy/dashboard/src/components/VirtualList.js
  packages/@uppy/google-drive/src/DriveProviderViews.js
  packages/@uppy/provider-views/src/Breadcrumbs.js
  packages/@uppy/transloadit/src/index.js
  packages/@uppy/tus/src/index.js
  packages/@uppy/utils/src/getFileTypeExtension.js
  website/src/docs/tus.md
  website/themes/uppy/source/css/_page.scss
  website/themes/uppy/source/js/common.js
Labels: 2.0

#2957 Always enable strict types and remove `.run` method
  examples/vue/package-lock.json
  examples/vue3/package-lock.json
  packages/@uppy/aws-s3-multipart/types/index.test-d.ts
  packages/@uppy/aws-s3/types/index.test-d.ts
  packages/@uppy/core/src/index.js
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/core/types/index.test-d.ts
  packages/@uppy/dashboard/types/index.test-d.ts
  packages/@uppy/drag-drop/types/index.test-d.ts
  packages/@uppy/google-drive/types/index.test-d.ts
  packages/@uppy/react/src/useUppy.d.ts
  packages/@uppy/react/types/index.test-d.tsx
  packages/@uppy/screen-capture/types/index.test-d.ts
  packages/@uppy/transloadit/types/index.test-d.ts
  packages/@uppy/webcam/types/index.test-d.ts
  packages/@uppy/xhr-upload/types/index.test-d.ts
  test/endtoend/typescript/main.ts
  website/src/docs/uppy.md
Labels: 2.0, Types

#2941 core: onBeforeFileAdded: pass full file object with extension, detected type, meta, size, etc
  packages/@uppy/core/src/index.js
Labels: 2.0

#2934 xhr: use symbol for internal options
  packages/@uppy/aws-s3-multipart/src/index.js
  packages/@uppy/aws-s3/src/MiniXHRUpload.js
  packages/@uppy/aws-s3/src/index.js
  packages/@uppy/tus/src/index.js
  packages/@uppy/utils/src/RateLimitedQueue.js
  packages/@uppy/utils/src/RateLimitedQueue.test.js
  packages/@uppy/utils/types/index.d.ts
  packages/@uppy/xhr-upload/src/index.js
Labels: 2.0

#2930 Improve checkbox for screenreaders
  packages/@uppy/core/src/index.js
  packages/@uppy/locales/src/en_US.js
  packages/@uppy/locales/src/fr_FR.js
  packages/@uppy/locales/src/nl_NL.js
  packages/@uppy/provider-views/src/Item/components/ListLi.js
Labels: Accessibility
