Repository transloadit/uppy, pull requests merged in 2021-08, with the labels that each got.

#3061 build: fix building on Node.js v14.x LTS
  .eslintrc.js
  package.json
  packages/@uppy/core/src/index.js
  packages/@uppy/dashboard/src/index.test.js
Labels: 2.0

#3060 Don’t show double error info message for required metafields
  packages/@uppy/core/src/index.js
Labels: 2.0

#3073 @uppy/core: use private properties in `UIPlugin`
  packages/@uppy/core/src/UIPlugin.js
Labels: 2.0

#3072 UIPlugin fix: prevent Preact replacing contents of body element by using createDocumentFragment
  examples/bundled/index.js
  packages/@uppy/box/types/index.d.ts
  packages/@uppy/box/types/index.test-d.ts
  packages/@uppy/core/src/UIPlugin.js
  packages/@uppy/dashboard/types/index.d.ts
  packages/@uppy/drag-drop/types/index.d.ts
  packages/@uppy/drag-drop/types/index.test-d.ts
  packages/@uppy/dropbox/types/index.d.ts
  packages/@uppy/dropbox/types/index.test-d.ts
  packages/@uppy/facebook/types/index.d.ts
  packages/@uppy/facebook/types/index.test-d.ts
  packages/@uppy/file-input/types/index.d.ts
  packages/@uppy/form/types/index.d.ts
  packages/@uppy/google-drive/types/index.d.ts
  packages/@uppy/informer/types/index.d.ts
  packages/@uppy/instagram/types/index.d.ts
  packages/@uppy/instagram/types/index.test-d.ts
  packages/@uppy/onedrive/types/index.d.ts
  packages/@uppy/onedrive/types/index.test-d.ts
  packages/@uppy/progress-bar/src/index.js
  packages/@uppy/progress-bar/types/index.d.ts
  packages/@uppy/progress-bar/types/index.test-d.ts
  packages/@uppy/react/src/CommonTypes.d.ts
  packages/@uppy/react/types/index.test-d.tsx
  packages/@uppy/status-bar/types/index.d.ts
  packages/@uppy/status-bar/types/index.test-d.ts
  packages/@uppy/unsplash/types/index.d.ts
  packages/@uppy/unsplash/types/index.test-d.ts
  packages/@uppy/url/types/index.d.ts
  packages/@uppy/url/types/index.test-d.ts
  packages/@uppy/webcam/types/index.d.ts
  packages/@uppy/zoom/types/index.d.ts
  packages/@uppy/zoom/types/index.test-d.ts
  website/src/_template/contributing.md
  website/src/docs/dashboard.md
  website/src/docs/informer.md
  website/src/docs/progressbar.md
  website/src/docs/statusbar.md
  website/src/examples/dashboard/app.es6
  website/src/examples/dashboard/index.ejs
  website/src/examples/xhrupload/app.es6
  website/themes/uppy/layout/index.ejs
Labels: 2.0

#3078 website: set background color on root element
  website/themes/uppy/source/css/_common.scss
Labels: Website

#3074 Fix webcam mirror option
  packages/@uppy/webcam/src/index.js
Labels: Webcam

#3069 Sort Google Drive list by name
  packages/@uppy/companion/src/server/provider/drive/index.js
  packages/@uppy/provider-views/src/Browser.js
  packages/@uppy/provider-views/src/ProviderView/ProviderView.js
Labels: Companion

#3076 @uppy/aws-s3: refactor to private fields
  packages/@uppy/aws-s3/src/index.js
Labels: 2.0

#3082 Revert "dashboard: mostly restore backwards compatibility for the `browse` strings
  packages/@uppy/dashboard/src/components/AddFiles.js
Labels: 2.0

#3088 Improve a11y of remove button in dashboard
  packages/@uppy/dashboard/src/components/FileItem/Buttons/index.js
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/locales/src/en_US.js
  packages/@uppy/locales/src/fr_FR.js
  packages/@uppy/locales/src/nl_NL.js
Labels: Dashboard, Accessibility

#3093 Create `onUnmount` in `UIPlugin` for plugins that require clean up
  packages/@uppy/core/src/BasePlugin.js
  packages/@uppy/core/src/UIPlugin.js
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/webcam/src/index.js
  website/src/docs/writing-plugins.md
Labels: Dashboard, Webcam, Core

#3094 @uppy/aws-s3: refactor to use private fields
  packages/@uppy/aws-s3/src/MiniXHRUpload.js
  packages/@uppy/utils/src/NetworkError.js
Labels: 2.0
