Repository transloadit/uppy, pull requests merged in 2021-07, with the labels that each got.

#2986 A bit of polish
  website/src/_posts/2021-07-1.30.md
Labels: Improvement

#2993 Set Tus and Xhr-Upload limit to 5
  packages/@uppy/tus/src/index.js
  packages/@uppy/xhr-upload/src/index.js
  website/src/docs/tus.md
  website/src/docs/xhrupload.md
Labels: 2.0

#2992 tools: lint JS code snippets inside blog posts
  .eslintignore
  website/src/_posts/2021-XX-XX.md
Labels: 2.0

#2996 Form: remove multiple results option
  packages/@uppy/form/src/index.js
  packages/@uppy/form/types/index.d.ts
  website/src/docs/form.md
Labels: 2.0

#2995 companion: Remove deprecated serverHeaders in favour of companionHeaders
  examples/custom-provider/client/MyCustomProvider.js
  packages/@uppy/box/src/index.js
  packages/@uppy/companion-client/src/RequestClient.js
  packages/@uppy/companion-client/types/index.d.ts
  packages/@uppy/dropbox/src/index.js
  packages/@uppy/facebook/src/index.js
  packages/@uppy/google-drive/src/index.js
  packages/@uppy/instagram/src/index.js
  packages/@uppy/onedrive/src/index.js
  packages/@uppy/robodog/src/addProviders.js
  packages/@uppy/transloadit/src/index.js
  packages/@uppy/url/src/index.js
  packages/@uppy/zoom/src/index.js
  website/src/_posts/2020-03-custom-providers.md
Labels: 2.0

#2994 Dashboard: show link to file upload result — false by default
  packages/@uppy/dashboard/src/index.js
  website/src/docs/dashboard.md
Labels: 2.0

#3001 @uppy/angular: fix types
  packages/@uppy/angular/projects/angular/src/lib/components/dashboard-modal/dashboard-modal.component.ts
  packages/@uppy/angular/projects/angular/src/lib/components/dashboard/dashboard.component.ts
  packages/@uppy/angular/projects/angular/src/lib/components/drag-drop/drag-drop.component.ts
  packages/@uppy/angular/projects/angular/src/lib/components/progress-bar/progress-bar.component.ts
  packages/@uppy/angular/projects/angular/src/lib/components/status-bar/status-bar.component.ts
  packages/@uppy/angular/projects/angular/src/lib/utils/wrapper.ts
  packages/@uppy/dashboard/types/index.d.ts
  packages/@uppy/drag-drop/types/index.d.ts
  packages/@uppy/progress-bar/types/index.d.ts
  packages/@uppy/react/src/Dashboard.d.ts
  packages/@uppy/react/src/DashboardModal.d.ts
  packages/@uppy/react/src/DragDrop.d.ts
  packages/@uppy/react/src/ProgressBar.d.ts
  packages/@uppy/react/src/StatusBar.d.ts
  packages/@uppy/status-bar/types/index.d.ts
  test/endtoend/typescript/main.ts
Labels: 2.0

#2980 Improve checkbox for screenreaders 2
  packages/@uppy/core/src/_utils.scss
  packages/@uppy/core/src/index.js
  packages/@uppy/locales/src/ar_SA.js
  packages/@uppy/locales/src/bg_BG.js
  packages/@uppy/locales/src/cs_CZ.js
  packages/@uppy/locales/src/da_DK.js
  packages/@uppy/locales/src/de_DE.js
  packages/@uppy/locales/src/el_GR.js
  packages/@uppy/locales/src/en_US.js
  packages/@uppy/locales/src/es_ES.js
  packages/@uppy/locales/src/fa_IR.js
  packages/@uppy/locales/src/fi_FI.js
  packages/@uppy/locales/src/fr_FR.js
  packages/@uppy/locales/src/gl_ES.js
  packages/@uppy/locales/src/he_IL.js
  packages/@uppy/locales/src/hr_HR.js
  packages/@uppy/locales/src/hu_HU.js
  packages/@uppy/locales/src/id_ID.js
  packages/@uppy/locales/src/is_IS.js
  packages/@uppy/locales/src/it_IT.js
  packages/@uppy/locales/src/ja_JP.js
  packages/@uppy/locales/src/ko_KR.js
  packages/@uppy/locales/src/nb_NO.js
  packages/@uppy/locales/src/nl_NL.js
  packages/@uppy/locales/src/pl_PL.js
  packages/@uppy/locales/src/pt_BR.js
  packages/@uppy/locales/src/pt_PT.js
  packages/@uppy/locales/src/ro_RO.js
  packages/@uppy/locales/src/ru_RU.js
  packages/@uppy/locales/src/sk_SK.js
  packages/@uppy/locales/src/sr_RS_Cyrillic.js
  packages/@uppy/locales/src/sr_RS_Latin.js
  packages/@uppy/locales/src/sv_SE.js
  packages/@uppy/locales/src/th_TH.js
  packages/@uppy/locales/src/tr_TR.js
  packages/@uppy/locales/src/uk_UA.js
  packages/@uppy/locales/src/vi_VN.js
  packages/@uppy/locales/src/zh_CN.js
  packages/@uppy/locales/src/zh_TW.js
  packages/@uppy/provider-views/src/Item/components/GridLi.js
  packages/@uppy/provider-views/src/Item/components/ListLi.js
  packages/@uppy/provider-views/src/style.scss
  packages/@uppy/provider-views/src/style/uppy-ProviderBrowser-viewType--grid.scss
  packages/@uppy/provider-views/src/style/uppy-ProviderBrowser-viewType--list.scss
  packages/@uppy/provider-views/src/style/uppy-ProviderBrowserItem-checkbox.scss
Labels: 2.0, Accessibility

#3002 @uppy/store-redux: force `new` keyword
  packages/@uppy/store-redux/src/index.js
  packages/@uppy/store-redux/src/index.test.js
  packages/@uppy/store-redux/types/index.d.ts
  packages/@uppy/store-redux/types/index.test-d.ts
Labels: 2.0

#3003 @uppy/store-redux: force `new` keyword
  packages/@uppy/store-redux/src/index.js
  packages/@uppy/store-redux/src/index.test.js
  packages/@uppy/store-redux/types/index.d.ts
  packages/@uppy/store-redux/types/index.test-d.ts
Labels: 2.0

#3007 angular: Fix broken packaging
  package.json
  packages/@uppy/angular/package.json
Labels: Angular, Build

#3009 @uppy/image-editor: fix SASS deprecation warning
  packages/@uppy/image-editor/src/inputrange.scss
Labels: 2.0

#3016 core: remove use of `Array.prototype.reduce` where possible
  examples/transloadit-textarea/main.js
  packages/@uppy/provider-views/src/SharedHandler.js
  website/src/examples/markdown-snippets/app.es6
Labels: 2.0

#3005 Call `upload-started` for every file instead of all at once in `xhr-upload`
  packages/@uppy/core/src/index.js
  packages/@uppy/xhr-upload/src/index.js
Labels: XHR Upload

#3035 @uppy/core: detach event listeners on close
  packages/@uppy/core/src/index.js
Labels: 2.0

#3045 @uppy/core: do not expose `plugins` property
  packages/@uppy/aws-s3/src/index.test.js
  packages/@uppy/core/src/index.js
  packages/@uppy/core/src/index.test.js
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/core/types/index.test-d.ts
  packages/@uppy/dashboard/types/index.test-d.ts
  packages/@uppy/url/types/index.test-d.ts
Labels: 2.0

#3042 @uppy/core: move event emitter to private properties
  packages/@uppy/core/src/index.js
Labels: 2.0

#3017 Support multiple messages in informer
  packages/@uppy/core/src/getFileName.js
  packages/@uppy/core/src/index.js
  packages/@uppy/core/src/index.test.js
  packages/@uppy/informer/package.json
  packages/@uppy/informer/src/FadeIn.js
  packages/@uppy/informer/src/index.js
  packages/@uppy/informer/src/style.scss
  packages/@uppy/provider-views/src/ProviderView/ProviderView.js
Labels: 2.0

#3043 @uppy/core: avoid binding methods to instance in constructor
  packages/@uppy/core/src/BasePlugin.js
  packages/@uppy/core/src/UIPlugin.js
  packages/@uppy/core/src/index.js
  packages/@uppy/dashboard/src/components/Dashboard.js
Labels: 2.0

#2969 Remove backwards compatibility hacks in locales
  BACKLOG.md
  bin/locale-packs.js
  packages/@uppy/core/src/index.js
  packages/@uppy/core/src/index.test.js
  packages/@uppy/dashboard/src/components/AddFiles.js
  packages/@uppy/dashboard/src/index.js
  packages/@uppy/locales/src/ar_SA.js
  packages/@uppy/locales/src/bg_BG.js
  packages/@uppy/locales/src/cs_CZ.js
  packages/@uppy/locales/src/da_DK.js
  packages/@uppy/locales/src/de_DE.js
  packages/@uppy/locales/src/el_GR.js
  packages/@uppy/locales/src/en_US.js
  packages/@uppy/locales/src/es_ES.js
  packages/@uppy/locales/src/fa_IR.js
  packages/@uppy/locales/src/fi_FI.js
  packages/@uppy/locales/src/fr_FR.js
  packages/@uppy/locales/src/gl_ES.js
  packages/@uppy/locales/src/he_IL.js
  packages/@uppy/locales/src/hr_HR.js
  packages/@uppy/locales/src/hu_HU.js
  packages/@uppy/locales/src/id_ID.js
  packages/@uppy/locales/src/is_IS.js
  packages/@uppy/locales/src/it_IT.js
  packages/@uppy/locales/src/ja_JP.js
  packages/@uppy/locales/src/ko_KR.js
  packages/@uppy/locales/src/nb_NO.js
  packages/@uppy/locales/src/nl_NL.js
  packages/@uppy/locales/src/pl_PL.js
  packages/@uppy/locales/src/pt_BR.js
  packages/@uppy/locales/src/pt_PT.js
  packages/@uppy/locales/src/ro_RO.js
  packages/@uppy/locales/src/ru_RU.js
  packages/@uppy/locales/src/sk_SK.js
  packages/@uppy/locales/src/sr_RS_Cyrillic.js
  packages/@uppy/locales/src/sr_RS_Latin.js
  packages/@uppy/locales/src/sv_SE.js
  packages/@uppy/locales/src/th_TH.js
  packages/@uppy/locales/src/tr_TR.js
  packages/@uppy/locales/src/uk_UA.js
  packages/@uppy/locales/src/vi_VN.js
  packages/@uppy/locales/src/zh_CN.js
  packages/@uppy/locales/src/zh_TW.js
  website/src/docs/dashboard.md
  website/src/docs/uppy.md
Labels: 2.0

#3041 @uppy/core: move more internals to private properties
  packages/@uppy/core/src/index.js
  packages/@uppy/core/src/index.test.js
Labels: 2.0

#3057 @uppy/companion-client: migrate to private properties
  packages/@uppy/companion-client/src/RequestClient.js
  packages/@uppy/companion-client/src/Socket.js
  packages/@uppy/companion-client/src/Socket.test.js
  packages/@uppy/companion-client/types/index.d.ts
Labels: 2.0

#3037 Add `croppedCanvasOptions` to image editor `opts`
  packages/@uppy/image-editor/src/Editor.js
  packages/@uppy/image-editor/src/index.js
  packages/@uppy/image-editor/types/index.d.ts
  website/src/docs/image-editor.md
Labels: 2.0
