Repository transloadit/uppy, pull requests merged in 2022-08, with the labels that each got.

#3932 @uppy/drop-target: remove `isFileTransfer` from the public API
  packages/@uppy/drop-target/src/index.js
Labels: 3.0

#3933 @uppy/dashboard: fix TODO
  packages/@uppy/dashboard/src/utils/copyToClipboard.js
Labels: 3.0

#3934 @uppy/url: remove private methods from public API
  packages/@uppy/url/src/Url.jsx
Labels: pending end-to-end tests, 3.0

#3931 @uppy/informer: simplify `render` method
  packages/@uppy/informer/src/TransitionGroup.js
Labels: 3.0

#3927 @uppy/transloadit: remove static properties in favor of exports
  packages/@uppy/transloadit/src/index.js
Labels: pending end-to-end tests, 3.0

#3929 @uppy/status-bar: rename internal modules
  packages/@uppy/react/src/StatusBar.js
  packages/@uppy/status-bar/src/StatusBar.jsx
  packages/@uppy/status-bar/src/StatusBarUI.jsx
  packages/@uppy/status-bar/src/_StatusBar.jsx
  packages/@uppy/status-bar/src/index.js
Labels: pending end-to-end tests, 3.0

#3930 @uppy/screen-capture: fix TODOs
  packages/@uppy/screen-capture/src/RecorderScreen.jsx
  packages/@uppy/screen-capture/src/ScreenCapture.jsx
  packages/@uppy/screen-capture/src/StopWatch.jsx
Labels: pending end-to-end tests, 3.0

#3937 @uppy/transloadit: send `assembly-cancelled` only once
  e2e/cypress/integration/dashboard-transloadit.spec.ts
  packages/@uppy/transloadit/src/index.js
Labels: pending end-to-end tests

#3941 @uppy/remote-sources: do not rely on `.name` property
  packages/@uppy/remote-sources/src/index.js
Labels: pending end-to-end tests, 3.0

#3928 @uppy/store-default: export the class, don't expose `.callbacks`
  packages/@uppy/core/src/Uppy.js
  packages/@uppy/core/types/index.test-d.ts
  packages/@uppy/store-default/README.md
  packages/@uppy/store-default/src/index.js
  packages/@uppy/store-default/src/index.test.js
  packages/@uppy/store-default/types/index.d.ts
  packages/@uppy/store-default/types/index.test-d.ts
  website/src/docs/stores.md
Labels: pending end-to-end tests, 3.0

#3912 Correctly handle errors for `prepareUploadParts`
  packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
  packages/@uppy/aws-s3-multipart/src/index.test.js
Labels: 3.0

#3942 Upgrade tus-js-client to 3.0.0
  packages/@uppy/companion/package.json
  packages/@uppy/tus/package.json
  yarn.lock
Labels: 3.0

#3850 example: fix aws-companion example
  .eslintrc.js
  examples/aws-companion/.gitignore
  examples/aws-companion/README.md
  examples/aws-companion/index.html
  examples/aws-companion/main.js
  examples/aws-companion/package.json
  examples/aws-companion/readme.md
  examples/aws-companion/server.cjs
  yarn.lock
Labels: 3.0

#3944 @uppy/companion: show deprecation message when using legacy s3 options
  packages/@uppy/companion/src/config/companion.js
Labels: pending end-to-end tests, 3.0

#3907 Fix all breaking todo comments for 3.0
  packages/@uppy/aws-s3-multipart/src/index.js
  packages/@uppy/companion/src/server/controllers/url.js
  packages/@uppy/core/src/BasePlugin.js
  packages/@uppy/core/src/Restricter.js
  packages/@uppy/core/src/Uppy.js
  packages/@uppy/core/src/Uppy.test.js
  packages/@uppy/core/src/index.js
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/dashboard/src/Dashboard.jsx
  packages/@uppy/react/src/Dashboard.js
  packages/@uppy/react/src/DashboardModal.js
  packages/@uppy/react/src/DragDrop.js
  packages/@uppy/react/src/ProgressBar.js
  packages/@uppy/react/src/StatusBar.js
  packages/@uppy/react/src/nonHtmlPropsHaveChanged.js
  packages/@uppy/redux-dev-tools/src/index.js
  packages/@uppy/store-redux/src/index.js
  packages/@uppy/store-redux/src/index.test.js
  packages/@uppy/thumbnail-generator/src/index.js
  packages/@uppy/thumbnail-generator/src/index.test.js
  packages/@uppy/transloadit/src/AssemblyOptions.js
  private/dev/Dashboard.js
  website/src/docs/core.md
  website/src/docs/dashboard.md
  website/src/docs/status-bar.md
Labels: 3.0

#3948 @uppy/companion: remove `isobject` from dependencies
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/server/header-blacklist.js
  yarn.lock
Labels: pending end-to-end tests, 3.0

#3950 @uppy/aws-s3-multipart: ignore exception inside `abortMultipartUpload`
  packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
  packages/@uppy/aws-s3-multipart/src/index.test.js
Labels: pending end-to-end tests, 3.0

#3949 @uppy/companion: upgrade `ws` version
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/server/socket.js
  yarn.lock
Labels: pending end-to-end tests, 3.0

#3963 Add compressor string translation to Japanese locale
  packages/@uppy/locales/src/ja_JP.js
Labels: pending end-to-end tests

#3975 Fix run example uppy-with-companion
  examples/uppy-with-companion/README.md
  examples/uppy-with-companion/package.json
  examples/uppy-with-companion/server/index.js
  yarn.lock
Labels: pending end-to-end tests

#3987 @uppy/transloadit: deprecate static properties, export new names
  packages/@uppy/transloadit/src/index.js
  packages/@uppy/transloadit/types/index.d.ts
  packages/@uppy/transloadit/types/index.test-d.ts
  packages/uppy/index.mjs
  website/src/docs/transloadit.md
  website/src/examples/transloadit/app.es6
Labels: pending end-to-end tests

#3989 @uppy/utils: add missing exports
  packages/@uppy/utils/package.json
  packages/@uppy/utils/types/index.d.ts
Labels: pending end-to-end tests

#3903 meta: upgrade all dev dependencies
  .yarn/patches/npm-auth-to-token-npm-1.0.0-c288ce201f
  .yarn/patches/preact-npm-10.10.0-dd04de05e8.patch
  .yarnrc.yml
  babel.config.js
  bin/build-bundle.mjs
  bin/build-css.js
  bin/build-lib.js
  e2e/package.json
  examples/angular-example/package.json
  examples/aws-companion/package.json
  examples/aws-presigned-url/package.json
  examples/node-xhr/package.json
  examples/php-xhr/package.json
  examples/python-xhr/package.json
  examples/svelte-example/package.json
  examples/vue3/package.json
  package.json
  packages/@uppy/angular/angular.json
  packages/@uppy/angular/package.json
  packages/@uppy/angular/projects/uppy/angular/package.json
  packages/@uppy/audio/package.json
  packages/@uppy/aws-s3-multipart/package.json
  packages/@uppy/aws-s3/package.json
  packages/@uppy/companion/package.json
  packages/@uppy/companion/test/__tests__/companion.js
  packages/@uppy/core/package.json
  packages/@uppy/core/types/index.test-d.ts
  packages/@uppy/dashboard/package.json
  packages/@uppy/form/package.json
  packages/@uppy/golden-retriever/package.json
  packages/@uppy/robodog/package.json
  packages/@uppy/status-bar/package.json
  packages/@uppy/store-redux/package.json
  packages/@uppy/store-redux/types/index.test-d.ts
  packages/@uppy/svelte/package.json
  packages/@uppy/thumbnail-generator/package.json
  packages/@uppy/transloadit/package.json
  packages/@uppy/tus/package.json
  packages/@uppy/xhr-upload/package.json
  packages/uppy/package.json
  private/dev/package.json
  private/locale-pack/package.json
  private/release/package.json
  website/package.json
  yarn.lock
Labels: pending end-to-end tests, 3.0

#3996 example: update Angular example to v14
  examples/angular-example/.browserslistrc
  examples/angular-example/.gitignore
  examples/angular-example/.vscode/extensions.json
  examples/angular-example/.vscode/launch.json
  examples/angular-example/.vscode/tasks.json
  examples/angular-example/README.md
  examples/angular-example/angular.json
  examples/angular-example/e2e/protractor.conf.js
  examples/angular-example/e2e/src/app.e2e-spec.ts
  examples/angular-example/e2e/src/app.po.ts
  examples/angular-example/e2e/tsconfig.json
  examples/angular-example/karma.conf.js
  examples/angular-example/package.json
  examples/angular-example/src/app/app.component.css
  examples/angular-example/src/app/app.component.html
  examples/angular-example/src/app/app.component.spec.ts
  examples/angular-example/src/app/app.component.ts
  examples/angular-example/src/app/app.module.ts
  examples/angular-example/src/environments/environment.ts
  examples/angular-example/src/polyfills.ts
  examples/angular-example/src/styles.css
  examples/angular-example/src/test.ts
  examples/angular-example/tsconfig.app.json
  examples/angular-example/tsconfig.json
  yarn.lock
Labels: pending end-to-end tests

#3997 @uppy/angular: upgrade to Angular 14
  packages/@uppy/angular/package.json
  packages/@uppy/angular/projects/uppy/angular/package.json
  yarn.lock
Labels: pending end-to-end tests

#4005 example: fix dependencies of `bundled` example
  examples/bundled/package.json
  yarn.lock
Labels: pending end-to-end tests

#4006 example: update to new CDN export names
  examples/cdn-example/index.html
  examples/uppy-with-companion/client/index.html
Labels: pending end-to-end tests

#4013 example: replace `transloadit-textarea` with `transloadit-markdown-bin`
  .eslintrc.js
  examples/transloadit-markdown-bin/README.md
  examples/transloadit-markdown-bin/index.html
  examples/transloadit-markdown-bin/main.js
  examples/transloadit-markdown-bin/package.json
  examples/transloadit-textarea/package.json
  examples/transloadit-textarea/template.json
  yarn.lock
Labels: pending end-to-end tests

#4007 example: migrate `multiple-instances` to ESM
  .eslintrc.js
  examples/multiple-instances/.gitignore
  examples/multiple-instances/README.md
  examples/multiple-instances/index.html
  examples/multiple-instances/main.js
  examples/multiple-instances/package.json
  yarn.lock
Labels: pending end-to-end tests

#4012 example: migrate `xhr-bundle` to ESM
  .eslintrc.js
  examples/xhr-bundle/.gitignore
  examples/xhr-bundle/README.md
  examples/xhr-bundle/index.html
  examples/xhr-bundle/main.js
  examples/xhr-bundle/package.json
  examples/xhr-bundle/server.cjs
  yarn.lock
Labels: pending end-to-end tests

#4008 example: migrate `node-xhr` to ESM
  .eslintrc.js
  examples/node-xhr/.gitignore
  examples/node-xhr/README.md
  examples/node-xhr/index.html
  examples/node-xhr/main.js
  examples/node-xhr/package.json
  examples/node-xhr/server.js
  yarn.lock
Labels: pending end-to-end tests

#4009 example: migrate `php-xhr` to ESM
  .eslintrc.js
  examples/php-xhr/.gitignore
  examples/php-xhr/README.md
  examples/php-xhr/index.html
  examples/php-xhr/main.js
  examples/php-xhr/package.json
  examples/php-xhr/requirements.txt
  examples/php-xhr/server.php
  yarn.lock
Labels: pending end-to-end tests

#4010 example: migrate `python-xhr` to ESM
  .eslintrc.js
  examples/python-xhr/.gitignore
  examples/python-xhr/README.md
  examples/python-xhr/index.html
  examples/python-xhr/main.js
  examples/python-xhr/package.json
  examples/python-xhr/server.py
  yarn.lock
Labels: pending end-to-end tests

#4017 example: fix svelte example
  examples/svelte-example/.gitignore
  examples/svelte-example/README.md
  examples/svelte-example/package.json
  examples/svelte-example/server.mjs
  yarn.lock
Labels: pending end-to-end tests

#4004 @uppy/react: move `@uppy/` packages to peer dependencies
  packages/@uppy/react/package.json
  website/src/docs/react-dashboard-modal.md
  website/src/docs/react-dashboard.md
  website/src/docs/react-dragdrop.md
  website/src/docs/react-fileinput.md
  website/src/docs/react-progressbar.md
  website/src/docs/react-statusbar.md
  website/src/docs/react.md
  yarn.lock
Labels: pending end-to-end tests, 3.0

#4019 @uppy/tus: avoid crashing when Tus client report an error before any …
  packages/@uppy/tus/src/index.js
Labels: pending end-to-end tests

#4023 @uppy/tus, @uppy/xhr-upload, @uppy/aws-s3: `metaFields` -> `allowedMetaFields`
  packages/@uppy/aws-s3/src/MiniXHRUpload.js
  packages/@uppy/aws-s3/src/index.js
  packages/@uppy/aws-s3/types/index.d.ts
  packages/@uppy/transloadit/src/index.js
  packages/@uppy/tus/src/index.js
  packages/@uppy/tus/types/index.d.ts
  packages/@uppy/xhr-upload/src/index.js
  packages/@uppy/xhr-upload/types/index.d.ts
  website/src/docs/aws-s3.md
  website/src/docs/tus.md
  website/src/docs/xhr-upload.md
Labels: 3.0

#4027 example: replace Robodog example with Transloadit + RemoteSources + Form
  examples/transloadit/README.md
  examples/transloadit/index.html
  examples/transloadit/main.js
  examples/transloadit/package.json
  examples/transloadit/server.cjs
  yarn.lock
Labels: pending end-to-end tests

#4015 example: migrate `digitalocean-spaces` to ESM
  .eslintrc.js
  examples/digitalocean-spaces/.gitignore
  examples/digitalocean-spaces/README.md
  examples/digitalocean-spaces/index.html
  examples/digitalocean-spaces/main.js
  examples/digitalocean-spaces/package.json
  examples/digitalocean-spaces/readme.md
  examples/digitalocean-spaces/server.cjs
  yarn.lock
Labels: pending end-to-end tests

#4029 meta: fix linter failures
  .eslintignore
  examples/transloadit/main.js
  examples/transloadit/rollup.config.js
  examples/transloadit/server.js
Labels: pending end-to-end tests

#4024 @uppy/vue: move `@uppy/` packages to peer dependencies
  packages/@uppy/vue/package.json
  website/src/docs/vue.md
  yarn.lock
Labels: 3.0

#4043 @uppy/utils: fix `relativePath` when drag&dropping a folder
  e2e/cypress/integration/dashboard-ui.spec.ts
  packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi/getRelativePath.js
  packages/@uppy/utils/src/getDroppedFiles/utils/webkitGetAsEntryApi/index.js
Labels: 2.0

#4065 @uppy/svelte: update peer dependencies
  packages/@uppy/svelte/package.json
  website/src/docs/migration-guides.md
  website/src/docs/svelte.md
  yarn.lock
Labels: pending end-to-end tests

#4072 @uppy/core: fix types
  packages/@uppy/core/types/index.d.ts
Labels: pending end-to-end tests

#4066 website: add `Known issues` section on Migration Guide
  website/src/docs/migration-guides.md
Labels: pending end-to-end tests
