Repository transloadit/uppy, pull requests merged in 2022-10, with the labels that each got.

#4136 Update pl_PL.js
  packages/@uppy/locales/src/pl_PL.js
Labels: pending end-to-end tests, hacktoberfest

#4145 Add missing Ukrainian locale entries
  packages/@uppy/locales/src/uk_UA.js
Labels: pending end-to-end tests

#4129 Add example for Uppy with S3 and a Node.js server
  .eslintrc.js
  .gitignore
  CHANGELOG.md
  examples/aws-nodejs/README.md
  examples/aws-nodejs/index.js
  examples/aws-nodejs/package.json
  examples/aws-nodejs/public/drag.html
  examples/aws-nodejs/public/index.html
  examples/aws-php/.gitignore
  examples/aws-php/composer.json
  examples/aws-php/composer.lock
  examples/aws-php/index.html
  examples/aws-php/main.js
  examples/aws-php/package.json
  examples/aws-php/readme.md
  examples/aws-php/s3-sign.php
  examples/aws-php/serve.php
  website/src/docs/aws-s3.md
  yarn.lock
Labels: pending end-to-end tests

#4143 @uppy/url: Trim whitespace around user input url
  packages/@uppy/url/src/UrlUI.jsx
Labels: pending end-to-end tests

#4099 @uppy/webcam: fix bug when Dashboard is using a custom id
  packages/@uppy/core/src/UIPlugin.js
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/webcam/src/Webcam.jsx
Labels: safe to test, pending end-to-end tests

#4161 @uppy/core: make cancel() and close() arguments optional in types
  packages/@uppy/core/types/index.d.ts
Labels: Types, Core
