Repository transloadit/uppy, pull requests merged in 2022-05, with the labels that each got.

#3683 @uppy/google-drive: refactor to ESM
  .eslintrc.js
  packages/@uppy/google-drive/package.json
  packages/@uppy/google-drive/src/DriveProviderViews.js
  packages/@uppy/google-drive/src/GoogleDrive.jsx
  packages/@uppy/google-drive/src/index.js
  packages/@uppy/google-drive/src/locale.js
  website/src/docs/google-drive.md
Labels: pending end-to-end tests

#3678 Add `save` translation to Spanish locale
  packages/@uppy/locales/src/es_ES.js
Labels: pending end-to-end tests

#3685 @uppy/image-editor: refactor to ESM
  .eslintrc.js
  packages/@uppy/image-editor/package.json
  packages/@uppy/image-editor/src/Editor.jsx
  packages/@uppy/image-editor/src/ImageEditor.jsx
  packages/@uppy/image-editor/src/index.js
  packages/@uppy/image-editor/src/locale.js
  website/src/docs/image-editor.md
Labels: pending end-to-end tests

#3686 @uppy/webcam: refactor to ESM
  .eslintrc.js
  packages/@uppy/webcam/package.json
  packages/@uppy/webcam/src/CameraIcon.jsx
  packages/@uppy/webcam/src/CameraScreen.jsx
  packages/@uppy/webcam/src/DiscardButton.jsx
  packages/@uppy/webcam/src/PermissionsScreen.js
  packages/@uppy/webcam/src/PermissionsScreen.jsx
  packages/@uppy/webcam/src/RecordButton.jsx
  packages/@uppy/webcam/src/RecordingLength.jsx
  packages/@uppy/webcam/src/SnapshotButton.jsx
  packages/@uppy/webcam/src/SubmitButton.jsx
  packages/@uppy/webcam/src/VideoSourceSelect.jsx
  packages/@uppy/webcam/src/Webcam.jsx
  packages/@uppy/webcam/src/Webcam.test.js
  packages/@uppy/webcam/src/formatSeconds.js
  packages/@uppy/webcam/src/formatSeconds.test.js
  packages/@uppy/webcam/src/index.js
  packages/@uppy/webcam/src/locale.js
  packages/@uppy/webcam/src/supportsMediaRecorder.js
  packages/@uppy/webcam/src/supportsMediaRecorder.test.js
  website/src/docs/webcam.md
Labels: pending end-to-end tests

#3709 export interface AwsS3MultipartOptions
  packages/@uppy/aws-s3-multipart/types/index.d.ts
Labels: pending end-to-end tests

#3707 @uppy/locales: refactor to ESM
  .eslintrc.js
  packages/@uppy/locales/package.json
  packages/@uppy/locales/src/ar_SA.js
  packages/@uppy/locales/src/bg_BG.js
  packages/@uppy/locales/src/cs_CZ.js
  packages/@uppy/locales/src/da_DK.js
  packages/@uppy/locales/src/de_DE.js
  packages/@uppy/locales/src/el_GR.js
  packages/@uppy/locales/src/en_US.js
  packages/@uppy/locales/src/es_ES.js
  packages/@uppy/locales/src/fa_IR.js
  packages/@uppy/locales/src/fi_FI.js
  packages/@uppy/locales/src/fr_FR.js
  packages/@uppy/locales/src/gl_ES.js
  packages/@uppy/locales/src/he_IL.js
  packages/@uppy/locales/src/hr_HR.js
  packages/@uppy/locales/src/hu_HU.js
  packages/@uppy/locales/src/id_ID.js
  packages/@uppy/locales/src/is_IS.js
  packages/@uppy/locales/src/it_IT.js
  packages/@uppy/locales/src/ja_JP.js
  packages/@uppy/locales/src/ko_KR.js
  packages/@uppy/locales/src/nb_NO.js
  packages/@uppy/locales/src/nl_NL.js
  packages/@uppy/locales/src/pl_PL.js
  packages/@uppy/locales/src/pt_BR.js
  packages/@uppy/locales/src/pt_PT.js
  packages/@uppy/locales/src/ro_RO.js
  packages/@uppy/locales/src/ru_RU.js
  packages/@uppy/locales/src/sk_SK.js
  packages/@uppy/locales/src/sr_RS_Cyrillic.js
  packages/@uppy/locales/src/sr_RS_Latin.js
  packages/@uppy/locales/src/sv_SE.js
  packages/@uppy/locales/src/th_TH.js
  packages/@uppy/locales/src/tr_TR.js
  packages/@uppy/locales/src/uk_UA.js
  packages/@uppy/locales/src/vi_VN.js
  packages/@uppy/locales/src/zh_CN.js
  packages/@uppy/locales/src/zh_TW.js
  packages/@uppy/locales/template.js
Labels: pending end-to-end tests

#3706 @uppy/progress-bar: refactor to ESM
  .eslintrc.js
  packages/@uppy/progress-bar/package.json
  packages/@uppy/progress-bar/src/ProgressBar.jsx
  packages/@uppy/progress-bar/src/index.js
Labels: pending end-to-end tests

#3713 @uppy/url: refactor to ESM
  .eslintrc.js
  packages/@uppy/url/package.json
  packages/@uppy/url/src/Url.jsx
  packages/@uppy/url/src/UrlUI.jsx
  packages/@uppy/url/src/index.js
  packages/@uppy/url/src/locale.js
  packages/@uppy/url/src/utils/forEachDroppedOrPastedUrl.js
  website/src/docs/url.md
Labels: pending end-to-end tests

#3699 @uppy/zoom: refactor to ESM
  .eslintrc.js
  packages/@uppy/zoom/package.json
  packages/@uppy/zoom/src/Zoom.jsx
  packages/@uppy/zoom/src/index.js
  packages/@uppy/zoom/src/locale.js
  website/src/docs/zoom.md
Labels: pending end-to-end tests

#3694 @uppy/onedrive: refactor to ESM
  .eslintrc.js
  packages/@uppy/onedrive/package.json
  packages/@uppy/onedrive/src/OneDrive.jsx
  packages/@uppy/onedrive/src/index.js
  packages/@uppy/onedrive/src/locale.js
  website/src/docs/onedrive.md
Labels: pending end-to-end tests

#3729 @uppy/tus: fix broken import
  packages/@uppy/tus/src/getFingerprint.js
  packages/@uppy/tus/src/index.js
Labels: pending end-to-end tests

#3732 @uppy/Informer: refactor to ESM
  .eslintrc.js
  packages/@uppy/informer/package.json
  packages/@uppy/informer/src/FadeIn.jsx
  packages/@uppy/informer/src/Informer.jsx
  packages/@uppy/informer/src/TransitionGroup.js
  packages/@uppy/informer/src/index.js
Labels: pending end-to-end tests

#3733 @uppy/redux-dev-tools: refactor to ESM
  .eslintrc.js
  packages/@uppy/redux-dev-tools/package.json
  packages/@uppy/redux-dev-tools/src/index.js
Labels: pending end-to-end tests

#3734 @uppy/thumbnail-generator: refactor to ESM
  .eslintrc.js
  packages/@uppy/thumbnail-generator/package.json
  packages/@uppy/thumbnail-generator/src/index.js
  packages/@uppy/thumbnail-generator/src/index.test.js
  packages/@uppy/thumbnail-generator/src/locale.js
  website/src/docs/thumbnail-generator.md
  yarn.lock
Labels: pending end-to-end tests

#3737 @uppy/informer: remove remaining `require` call
  packages/@uppy/informer/src/TransitionGroup.js
Labels: pending end-to-end tests

#3731 @uppy/golden-retriever: refactor to ESM
  .eslintrc.js
  packages/@uppy/golden-retriever/package.json
  packages/@uppy/golden-retriever/src/IndexedDBStore.js
  packages/@uppy/golden-retriever/src/MetaDataStore.js
  packages/@uppy/golden-retriever/src/ServiceWorker.js
  packages/@uppy/golden-retriever/src/ServiceWorkerStore.js
  packages/@uppy/golden-retriever/src/cleanup.js
  packages/@uppy/golden-retriever/src/index.js
Labels: pending end-to-end tests

#3712 @uppy/tus: wait for user promise on beforeRequest
  packages/@uppy/tus/src/index.js
Labels: pending end-to-end tests

#3745 @uppy/store-redux: refactor to ESM
  .eslintrc.js
  packages/@uppy/store-redux/package.json
  packages/@uppy/store-redux/src/index.js
  packages/@uppy/store-redux/src/index.test.js
  yarn.lock
Labels: pending end-to-end tests

#3746 @uppy/store-default: refactor to ESM
  .eslintrc.js
  packages/@uppy/store-default/package.json
  packages/@uppy/store-default/src/index.js
  packages/@uppy/store-default/src/index.test.js
Labels: pending end-to-end tests

#3754 meta: resolve linter warnings in `.d.ts` files
  .eslintrc.js
  packages/@uppy/core/types/index.d.ts
Labels: pending end-to-end tests

#3753 meta: fix linter warnings
  packages/uppy/index.js
  private/dev/index.js
  private/dev/sw.js
  private/locale-pack/test.mjs
  website/src/docs/tus.md
Labels: pending end-to-end tests

#3778 @uppy/image-editor: remove CJS-interop hack in the source code
  bin/build-lib.js
  packages/@uppy/image-editor/src/Editor.jsx
Labels: pending end-to-end tests

#3766 @uppy/dashboard: use webkitRelativePath when querying a file's relative path
  packages/@uppy/dashboard/src/Dashboard.jsx
Labels: pending end-to-end tests

#3780 @uppy/react: refactor to ESM
  .eslintrc.js
  packages/@uppy/dashboard/src/Dashboard.jsx
  packages/@uppy/drag-drop/src/DragDrop.jsx
  packages/@uppy/file-input/src/FileInput.jsx
  packages/@uppy/progress-bar/src/ProgressBar.jsx
  packages/@uppy/react/index.js
  packages/@uppy/react/index.mjs
  packages/@uppy/react/package.json
  packages/@uppy/react/src/Dashboard.js
  packages/@uppy/react/src/DashboardModal.js
  packages/@uppy/react/src/DragDrop.js
  packages/@uppy/react/src/FileInput.js
  packages/@uppy/react/src/ProgressBar.js
  packages/@uppy/react/src/StatusBar.js
  packages/@uppy/react/src/Wrapper.js
  packages/@uppy/react/src/getHTMLProps.js
  packages/@uppy/react/src/index.js
  packages/@uppy/react/src/nonHtmlPropsHaveChanged.js
  packages/@uppy/react/src/propTypes.js
  packages/@uppy/react/src/useUppy.js
  packages/@uppy/status-bar/src/_StatusBar.jsx
Labels: 🔮 Long-term, 3.0

#3752 @uppy/companion: fix some linter warnings
  .eslintrc.js
  packages/@uppy/companion/src/server/helpers/utils.js
  packages/@uppy/companion/src/server/logger.js
  packages/@uppy/companion/src/server/provider/box/index.js
  packages/@uppy/companion/src/server/provider/onedrive/index.js
  packages/@uppy/companion/src/server/provider/unsplash/adapter.js
  packages/@uppy/companion/src/server/redis.js
Labels: Companion

#3747 uppy: add Zoom plugin to the bundle and fix ESM exports
  packages/uppy/index.js
  packages/uppy/index.mjs
  packages/uppy/package.json
  yarn.lock
Labels: pending end-to-end tests
