Repository transloadit/uppy, pull requests merged in 2022-07, with the labels that each got.

#3854 example: fix `custom-provider` example
  .eslintrc.js
  examples/custom-provider/.gitignore
  examples/custom-provider/README.md
  examples/custom-provider/babel.config.js
  examples/custom-provider/client/MyCustomProvider.jsx
  examples/custom-provider/client/main.js
  examples/custom-provider/index.html
  examples/custom-provider/output/.empty
  examples/custom-provider/package.json
  examples/custom-provider/readme.md
  examples/custom-provider/server/CustomProvider.cjs
  examples/custom-provider/server/customprovider.js
  examples/custom-provider/server/index.cjs
  yarn.lock
Labels: 3.0

#3852 de-dupe companion dev docs
  .github/CONTRIBUTING.md
  website/src/docs/companion.md
Labels: 📖 Docs

#3873 @uppy/robodog,@uppy/transloadit: use modern syntax to simplify code
  packages/@uppy/robodog/src/TransloaditFormResult.js
  packages/@uppy/transloadit/src/index.js
Labels: pending end-to-end tests

#3869 @uppy/companion: remove `COMPANION_S3_GETKEY_SAFE_BEHAVIOR` env variable
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/companion.js
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/standalone/helper.js
  yarn.lock
Labels: Companion, 3.0

#3875 @uppy/image-editor: Add image editor cancel event
  packages/@uppy/dashboard/src/components/FileCard/index.jsx
  packages/@uppy/image-editor/src/ImageEditor.jsx
  packages/@uppy/image-editor/types/index.d.ts
  packages/@uppy/image-editor/types/index.test-d.ts
  website/src/docs/image-editor.md
Labels: pending end-to-end tests

#3883 Fix broken link in _posts/2017-03-0.15.md
  website/src/_posts/2017-03-0.15.md
Labels: pending end-to-end tests

#3882 meta: upgrade to Vite v3
  examples/custom-provider/package.json
  examples/vue/package.json
  examples/vue3/package.json
  private/dev/package.json
  yarn.lock
Labels: 3.0

#3871 meta: use `node:` protocol when using Node.js built-in core modules
  .eslintrc.js
  bin/build-css.js
  bin/build-lib.js
  bin/upload-to-cdn.js
  examples/angular-example/e2e/protractor.conf.js
  examples/angular-example/karma.conf.js
  examples/aws-companion/server.js
  examples/digitalocean-spaces/server.js
  examples/node-xhr/server.js
  examples/svelte-example/rollup.config.js
  examples/transloadit/main.js
  examples/transloadit/server.js
  package.json
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/config/companion.js
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/server/controllers/oauth-redirect.js
  packages/@uppy/companion/src/server/controllers/send-token.js
  packages/@uppy/companion/src/server/controllers/url.js
  packages/@uppy/companion/src/server/emitter/default-emitter.js
  packages/@uppy/companion/src/server/helpers/oauth-state.js
  packages/@uppy/companion/src/server/helpers/request.js
  packages/@uppy/companion/src/server/helpers/utils.js
  packages/@uppy/companion/src/server/jobs.js
  packages/@uppy/companion/src/server/logger.js
  packages/@uppy/companion/src/server/provider/box/adapter.js
  packages/@uppy/companion/src/server/provider/box/index.js
  packages/@uppy/companion/src/server/provider/drive/adapter.js
  packages/@uppy/companion/src/server/provider/drive/index.js
  packages/@uppy/companion/src/server/provider/dropbox/adapter.js
  packages/@uppy/companion/src/server/provider/dropbox/index.js
  packages/@uppy/companion/src/server/provider/facebook/adapter.js
  packages/@uppy/companion/src/server/provider/facebook/index.js
  packages/@uppy/companion/src/server/provider/instagram/graph/adapter.js
  packages/@uppy/companion/src/server/provider/instagram/graph/index.js
  packages/@uppy/companion/src/server/provider/onedrive/adapter.js
  packages/@uppy/companion/src/server/provider/onedrive/index.js
  packages/@uppy/companion/src/server/provider/unsplash/adapter.js
  packages/@uppy/companion/src/server/provider/unsplash/index.js
  packages/@uppy/companion/src/server/provider/zoom/index.js
  packages/@uppy/companion/src/standalone/helper.js
  packages/@uppy/companion/src/standalone/index.js
  packages/@uppy/companion/test/__mocks__/purest.js
  packages/@uppy/companion/test/__tests__/http-agent.js
  packages/@uppy/companion/test/__tests__/uploader.js
  website/build-examples.js
  website/inject.js
  website/private_modules/hexo-renderer-uppyexamples/index.js
  website/scripts/highlight.js
  yarn.lock
Labels: pending end-to-end tests, 3.0

#3589 @uppy/companion: upgrade `redis` to version 4.x
  .yarn/patches/@types-connect-redis-npm-0.0.18-4fd2b614d3
  examples/angular-example/package.json
  package.json
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/server/emitter/redis-emitter.js
  packages/@uppy/companion/src/server/redis.js
  packages/@uppy/companion/src/server/socket.js
  yarn.lock
Labels: Companion, 🔮 Long-term, pending end-to-end tests

#3902 @uppy/companion: update minimal supported Node.js version in the docs
  website/src/docs/companion.md
Labels: pending end-to-end tests

#3904 upgrade `nanoid` to v4
  packages/@uppy/aws-s3/package.json
  packages/@uppy/core/package.json
  packages/@uppy/dashboard/package.json
  packages/@uppy/store-redux/package.json
  packages/@uppy/xhr-upload/package.json
  yarn.lock
Labels: 3.0

#3895 aws-s3-multipart: make `headers` part indexed too in `prepareUploadParts`
  package.json
  packages/@uppy/aws-s3-multipart/src/MultipartUploader.js
  packages/@uppy/aws-s3-multipart/src/index.test.js
  packages/@uppy/aws-s3-multipart/types/index.d.ts
  packages/@uppy/aws-s3-multipart/types/index.test-d.ts
  website/inject.js
  website/src/docs/aws-s3-multipart.md
Labels: AWS S3, 3.0

#3921 doc: Fix typo in image-editor.md
  website/src/docs/image-editor.md
Labels: pending end-to-end tests

#3923 @uppy/tus: fix dependencies
  packages/@uppy/tus/package.json
  yarn.lock
Labels: pending end-to-end tests
