Repository transloadit/uppy, pull requests merged in 2022-06, with the labels that each got.

#3788 enable passing optional meta data to Uppy URL plugin's addFile API
  packages/@uppy/url/src/Url.jsx
  packages/@uppy/url/types/index.d.ts
Labels: pending end-to-end tests

#3770 (aws-s3-multipart) Allow companionHeaders to be modified before uploading files
  packages/@uppy/aws-s3-multipart/src/index.js
  packages/@uppy/aws-s3-multipart/src/index.test.js
  packages/@uppy/aws-s3/src/index.js
  packages/@uppy/aws-s3/src/index.test.js
  packages/@uppy/companion-client/src/RequestClient.js
Labels: AWS S3, pending end-to-end tests

#3802 example: update Vue2 example
  examples/vue/README.md
  examples/vue/babel.config.js
  examples/vue/index.html
  examples/vue/package.json
  examples/vue/src/App.vue
  examples/vue/src/components/HelloWorld.vue
  examples/vue/vite.config.js
  package.json
  private/vue-template-compiler/package.json
  yarn.lock
Labels: pending end-to-end tests, 3.0

#3812 @uppy/core,@uppy/dashboard: fix types for some events
  packages/@uppy/core/types/index.d.ts
  packages/@uppy/core/types/index.test-d.ts
  packages/@uppy/dashboard/types/index.d.ts
  packages/@uppy/dashboard/types/index.test-d.ts
Labels: Types, pending end-to-end tests, 3.0

#3807 uppy: refactor bundle package to ESM
  .eslintrc.js
  bin/build-bundle.mjs
  packages/uppy/bundle-legacy.js
  packages/uppy/bundle-legacy.mjs
  packages/uppy/bundle.js
  packages/uppy/bundle.mjs
  packages/uppy/index.js
  packages/uppy/index.mjs
  packages/uppy/package.json
Labels: pending end-to-end tests, 3.0

#3820 @uppy/transloadit: fix `COMPANION_PATTERN` export
  packages/@uppy/transloadit/src/index.js
Labels: pending end-to-end tests

#3809 meta: fix release process for beta branch
  .github/workflows/release.yml
  private/release/autoFixConflicts.js
  private/release/choose-semverness.js
  private/release/commit-and-open-pr.js
  private/release/config.js
  private/release/getUpToDateRefsFromGitHub.js
  private/release/interactive.js
Labels: 3.0

#3838 docs: Fix typo in aws-s3-multipart.md
  website/src/docs/aws-s3-multipart.md
Labels: pending end-to-end tests

#3839 Add missing translations and reorder
  packages/@uppy/locales/src/nl_NL.js
Labels: pending end-to-end tests

#3841 Build an ARM64 container
  .github/workflows/companion-deploy.yml
  Dockerfile
Labels: pending end-to-end tests

#3826 Companion 3 default to no s3 acl
  packages/@uppy/companion/src/config/companion.js
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/standalone/helper.js
  website/src/docs/companion.md
Labels: 3.0
