Repository transloadit/uppy, pull requests merged in 2023-03, with the labels that each got.

#4347 @uppy/dashboard: Fix low-contrast hover styles
  packages/@uppy/core/src/_variables.scss
  packages/@uppy/dashboard/src/style.scss
Labels: UI, Dashboard

#4362 @uppy/companion: fix typo in redis-emitter.js
  packages/@uppy/companion/src/server/emitter/redis-emitter.js
Labels: pending end-to-end tests

#4158 example: migrate `redux` to ESM
  .eslintrc.js
  examples/redux/.gitignore
  examples/redux/README.md
  examples/redux/index.html
  examples/redux/main.js
  examples/redux/package.json
  yarn.lock
Labels: pending end-to-end tests

#4330 @uppy/companion: merge Provider/SearchProvider
  packages/@uppy/companion/src/companion.js
  packages/@uppy/companion/src/server/middlewares.js
  packages/@uppy/companion/src/server/provider/Provider.js
  packages/@uppy/companion/src/server/provider/SearchProvider.js
  packages/@uppy/companion/src/server/provider/index.js
  packages/@uppy/companion/src/server/provider/unsplash/index.js
  packages/@uppy/companion/test/__tests__/provider-manager.js
  packages/@uppy/companion/test/__tests__/providers.js
Labels: semver-major
