Repository transloadit/uppy, pull requests merged in 2024-05, with the labels that each got.

#5120 Update ru_RU locale
  packages/@uppy/locales/src/ru_RU.ts
Labels: pending end-to-end tests

#5094 @uppy/xhr-upload: introduce hooks similar to tus
  docs/uploader/xhr.mdx
  packages/@uppy/utils/src/fetcher.ts
  packages/@uppy/xhr-upload/src/index.test.ts
  packages/@uppy/xhr-upload/src/index.ts
Labels: 4.0

#5156 @uppy/image-editor: fix tooltips
  packages/@uppy/image-editor/src/Editor.tsx
Labels: pending end-to-end tests

#4623 @uppy/companion: switch from `node-redis` to `ioredis`
  docs/companion.md
  e2e/mock-server.mjs
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/server/emitter/redis-emitter.js
  packages/@uppy/companion/src/server/redis.js
  packages/@uppy/companion/src/standalone/helper.js
  yarn.lock
Labels: 4.0

#5119 @uppy/companion: upgrade deps
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/server/Uploader.js
  yarn.lock
Labels: 4.0

#5093 docs: update `@uppy/aws-s3` docs
  docs/uploader/aws-s3-multipart.mdx
  docs/uploader/aws-s3.mdx
Labels: 4.0

#5174 meta: add MDX file to `lint-staged` list
  package.json
Labels: pending end-to-end tests

#5144 @uppy/companion: fix google drive gsuite export large size
  packages/@uppy/companion/src/server/provider/drive/index.js
  packages/@uppy/companion/test/__tests__/providers.js
  packages/@uppy/companion/test/fixtures/drive.js
Labels: pending end-to-end tests

#5182 @uppy/tus: fix no headers passed to companion if argument is a function
  packages/@uppy/tus/src/index.ts
Labels: pending end-to-end tests

#4824 @uppy/core: resolve some (breaking) TODOs
  packages/@uppy/core/src/Uppy.test.ts
  packages/@uppy/core/src/Uppy.ts
  packages/@uppy/core/src/__snapshots__/Uppy.test.ts.snap
  packages/@uppy/utils/src/FileProgress.ts
  packages/@uppy/utils/src/getSpeed.ts
Labels: 4.0

#5179 @uppy/xhr-upload: fix regression for lowercase HTTP methods
  docs/uploader/xhr.mdx
  packages/@uppy/xhr-upload/src/index.ts
Labels: pending end-to-end tests

#5159 @uppy/core: remove `reason`
  docs/uppy-core.mdx
  packages/@uppy/aws-s3/src/index.ts
  packages/@uppy/companion-client/src/RequestClient.ts
  packages/@uppy/core/src/Uppy.test.ts
  packages/@uppy/core/src/Uppy.ts
  packages/@uppy/transloadit/src/index.ts
  packages/@uppy/tus/src/index.ts
  packages/@uppy/xhr-upload/src/index.ts
Labels: pending end-to-end tests

#5136 @uppy/core: pass file to events consistently
  docs/uppy-core.mdx
  packages/@uppy/companion-client/src/RequestClient.ts
  packages/@uppy/core/src/EventManager.ts
  packages/@uppy/core/src/Uppy.ts
Labels: notable change
