Repository transloadit/uppy, pull requests merged in 2024-03, with the labels that each got.

#4997 @uppy/utils: fix `findAllDOMElements` type
  packages/@uppy/utils/src/findAllDOMElements.ts
Labels: pending end-to-end tests

#4994 meta: fix `resize-observer-polyfill` types
  .yarn/patches/resize-observer-polyfill-npm-1.5.1-603120e8a0.patch
  package.json
  yarn.lock
Labels: pending end-to-end tests

#4999 @uppy/dashboard: refactor to stable lifecycle method
  packages/@uppy/dashboard/src/components/Slide.jsx
Labels: pending end-to-end tests

#5001 @uppy/dashboard: add new `autoOpen` option
  packages/@uppy/dashboard/src/Dashboard.tsx
  packages/@uppy/dashboard/types/index.d.ts
  packages/@uppy/react/src/DashboardModal.js
Labels: pending end-to-end tests

#4970 @uppy/status-bar: remove default target
  packages/@uppy/status-bar/src/StatusBar.tsx
Labels: pending end-to-end tests, 4.0

#4971 @uppy/progress-bar: remove default target
  packages/@uppy/progress-bar/src/ProgressBar.tsx
Labels: pending end-to-end tests, 4.0

#5008 Upgrade to Angular 17.x and to TS 5.4
  e2e/package.json
  examples/angular-example/README.md
  examples/angular-example/angular.json
  examples/angular-example/package.json
  examples/angular-example/src/app/app.component.ts
  examples/svelte-example/package.json
  package.json
  packages/@uppy/angular/package.json
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal-demo.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard-modal/dashboard-modal.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard/dashboard-demo.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/dashboard/dashboard.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/drag-drop/drag-drop-demo.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/drag-drop/drag-drop.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar-demo.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/progress-bar/progress-bar.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/status-bar/status-bar-demo.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/components/status-bar/status-bar.component.ts
  packages/@uppy/angular/projects/uppy/angular/src/lib/utils/wrapper.ts
  packages/@uppy/angular/tsconfig.json
  packages/@uppy/companion/package.json
  yarn.lock
Labels: 4.0

#5044 meta: include more packages in `compare_diff` CI
  .github/workflows/e2e.yml
  package.json
Labels: pending end-to-end tests

#5046 meta: fix `watch:*` scripts
  package.json
Labels: pending end-to-end tests

#5043 @uppy/vue: migrate to Composition API with TS & drop Vue 2 support
  .eslintrc.js
  e2e/tsconfig.json
  examples/vue/.gitignore
  examples/vue/README.md
  examples/vue/index.html
  examples/vue/package.json
  examples/vue/src/App.vue
  examples/vue/src/main.js
  examples/vue/vite.config.js
  examples/vue3/package.json
  examples/vue3/src/App.vue
  packages/@uppy/file-input/src/index.ts
  packages/@uppy/vue/.npmignore
  packages/@uppy/vue/package.json
  packages/@uppy/vue/src/dashboard-modal.js
  packages/@uppy/vue/src/dashboard-modal.ts
  packages/@uppy/vue/src/dashboard.js
  packages/@uppy/vue/src/dashboard.ts
  packages/@uppy/vue/src/drag-drop.js
  packages/@uppy/vue/src/drag-drop.ts
  packages/@uppy/vue/src/file-input.js
  packages/@uppy/vue/src/file-input.ts
  packages/@uppy/vue/src/index.js
  packages/@uppy/vue/src/index.ts
  packages/@uppy/vue/src/progress-bar.js
  packages/@uppy/vue/src/progress-bar.ts
  packages/@uppy/vue/src/status-bar.js
  packages/@uppy/vue/src/status-bar.ts
  packages/@uppy/vue/src/useUppy.ts
  packages/@uppy/vue/src/utils.js
  packages/@uppy/vue/tsconfig.build.json
  packages/@uppy/vue/tsconfig.json
  yarn.lock
Labels: 4.0
