Repository transloadit/uppy, pull requests merged in 2024-04, with the labels that each got.

#4888 @uppy/core: use variadic arguments for `uppy.use`
  packages/@uppy/core/src/Uppy.test.ts
  packages/@uppy/core/src/Uppy.ts
  packages/@uppy/core/src/mocks/acquirerPlugin1.ts
  packages/@uppy/core/src/mocks/acquirerPlugin2.ts
  packages/@uppy/core/src/mocks/invalidPluginWithoutId.ts
  packages/@uppy/core/src/mocks/invalidPluginWithoutType.ts
Labels: pending end-to-end tests, 4.0

#5076 @uppy/aws-s3: default to multipart depending on the size of input
  packages/@uppy/aws-s3/src/index.test.ts
  packages/@uppy/aws-s3/src/index.ts
Labels: 4.0

#5035 @uppy/companion: bump Node.js version support matrix
  .github/workflows/companion.yml
  packages/@uppy/companion/package.json
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/server/controllers/connect.js
  packages/@uppy/companion/src/server/controllers/url.js
  packages/@uppy/companion/src/server/got.js
  packages/@uppy/companion/src/server/helpers/oauth-state.js
  packages/@uppy/companion/src/server/helpers/request.js
  packages/@uppy/companion/src/server/jobs.js
  packages/@uppy/companion/src/server/provider/box/index.js
  packages/@uppy/companion/src/server/provider/credentials.js
  packages/@uppy/companion/src/server/provider/drive/index.js
  packages/@uppy/companion/src/server/provider/dropbox/index.js
  packages/@uppy/companion/src/server/provider/facebook/index.js
  packages/@uppy/companion/src/server/provider/instagram/graph/index.js
  packages/@uppy/companion/src/server/provider/onedrive/index.js
  packages/@uppy/companion/src/server/provider/unsplash/index.js
  packages/@uppy/companion/src/server/provider/zoom/index.js
  packages/@uppy/companion/test/__tests__/http-agent.js
  packages/@uppy/companion/test/__tests__/uploader.js
  packages/@uppy/companion/tsconfig.json
  yarn.lock
Labels: 4.0

#5128 @uppy/companion: coerce `requestUrl` to a string
  packages/@uppy/companion/src/server/helpers/request.js
Labels: pending end-to-end tests

#4849 Upgrade Yarn to 4.x
  .eslintrc.js
  .github/workflows/bundlers.yml
  .yarn/patches/stylelint-config-rational-order-npm-0.1.2-d8336e84ed.patch
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarnrc.yml
  e2e/package.json
  examples/aws-php/package.json
  package.json
  packages/@uppy/companion/src/server/Uploader.js
  packages/@uppy/companion/src/server/helpers/request.js
  packages/@uppy/compressor/src/index.test.ts
  packages/@uppy/compressor/src/index.ts
  packages/@uppy/core/package.json
  packages/@uppy/dashboard/package.json
  packages/@uppy/dashboard/src/utils/copyToClipboard.ts
  packages/@uppy/store-redux/package.json
  packages/@uppy/transloadit/package.json
  packages/@uppy/url/package.json
  private/locale-pack/package.json
  private/release/getUpToDateRefsFromGitHub.js
  private/release/package.json
  private/remark-lint-uppy/package.json
  yarn.lock
Labels: 4.0
